### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by GePo00** [ddxfish/XPT2046_Bitbang_Arduino_Library#7]
What can we do if screen is in different orientation set by tft.setRotation(3)?
I miss a function like this
 ts.begin();
 ts.setRotation(3);

**Comment by ddxfish** [comment]
Your question is for the display driver, this is just the touchscreen driver. I use rotation in my touchscreen example though, similar syntax, line #379. Change your 3 to 1,2,3,4 to rotate your screen 90 degrees. 
[CYD-ESP32-LVGL-touch-example](https://github.com/ddxfish/CYD-ESP32-LVGL-touch-example/blob/main/CYD-LVGL/src/main.cpp)

Try your display driver first, and if you run out of all options you can simply flip x and y in the code for the touchscreen in this driver. Flip x and y just after polling the touchscreen. Replace with your x,y heights. Try all other options first, this is a workaround if this touchscreen driver doesn't fit your current needs and you have to flip the touchscreen.
```
y = 320 - y 
x = 240 - x
```

Good luck!
